In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("Solar_Power_Generation.csv")
data

,distance-to-solar-noon,temperature,wind-direction,wind-speed,sky-cover,visibility,humidity,average-wind-speed-(period),average-pressure-(period),power-generated
0,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
1,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
3,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
4,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069
...,...,...,...,...,...,...,...,...,...,...
100452,0.161450,50,28,18.7,3,10.0,72,21.0,30.05,19435
100453,0.457990,50,28,18.7,3,10.0,72,21.0,29.99,4842
100454,0.754530,50,28,18.7,2,10.0,77,21.0,29.98,0
100455,1.051071,50,28,18.7,2,10.0,80,11.0,30.00,0
100456,1.021346,47,32,6.6,1,10.0,77,7.0,30.01,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100457 entries, 0 to 100456
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   distance-to-solar-noon       100457 non-null  float64
 1   temperature                  100457 non-null  int64
 2   wind-direction               100457 non-null  int64
 3   wind-speed                   100457 non-null  float64
 4   sky-cover                    100457 non-null  int64
 5   visibility                   100457 non-null  float64
 6   humidity                     100457 non-null  int64
 7   average-wind-speed-(period)  100422 non-null  float64
 8   average-pressure-(period)    100457 non-null  float64
 9   power-generated              100457 non-null  int64
dtypes: float64(5), int64(5)
memory usage: 7.7 MB

In [7]:
data.isnull().sum()

distance-to-solar-noon          0
temperature                     0
wind-direction                  0
wind-speed                      0
sky-cover                       0
visibility                      0
humidity                        0
average-wind-speed-(period)    35
average-pressure-(period)       0
power-generated                 0
dtype: int64

In [9]:
# Dataframe attributes
print(type(data))
print(data.shape)
print(data.size)

<class 'pandas.core.frame.DataFrame'>
(100457, 10)
1004570

In [25]:
data.dtypes

distance-to-solar-noon         float64
temperature                      int64
wind-direction                   int64
wind-speed                     float64
sky-cover                        int64
visibility                     float64
humidity                         int64
average-wind-speed-(period)    float64
average-pressure-(period)      float64
power-generated                  int64
dtype: object

In [27]:
data.describe()

,distance-to-solar-noon,temperature,wind-direction,wind-speed,sky-cover,visibility,humidity,average-wind-speed-(period),average-pressure-(period),power-generated
count,100457.000000,100457.000000,100457.000000,100457.000000,100457.000000,100457.000000,100457.000000,100422.000000,100457.000000,100457.000000
mean,0.504066,58.459550,24.929432,10.066112,1.985775,9.553889,73.516181,10.097220,30.018217,6956.069005
std,0.298413,6.850113,6.944246,4.836991,1.412807,1.389866,15.095488,7.254537,0.142204,10288.942235
min,0.050401,42.000000,1.000000,1.100000,0.000000,0.000000,14.000000,0.000000,29.480000,0.000000
25%,0.255367,53.000000,25.000000,6.600000,1.000000,10.000000,65.000000,5.000000,29.920000,0.000000
50%,0.480380,59.000000,27.000000,9.900000,2.000000,10.000000,77.000000,9.000000,30.000000,388.000000
75%,0.740418,63.000000,29.000000,13.100000,3.000000,10.000000,84.000000,15.000000,30.110000,12654.000000
max,1.141361,78.000000,36.000000,26.600000,4.000000,10.000000,100.000000,40.000000,30.530000,36580.000000

In [29]:
data[data.duplicated()]

,distance-to-solar-noon,temperature,wind-direction,wind-speed,sky-cover,visibility,humidity,average-wind-speed-(period),average-pressure-(period),power-generated
2920,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
2921,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2922,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
2923,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
2924,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069
...,...,...,...,...,...,...,...,...,...,...
100452,0.161450,50,28,18.7,3,10.0,72,21.0,30.05,19435
100453,0.457990,50,28,18.7,3,10.0,72,21.0,29.99,4842
100454,0.754530,50,28,18.7,2,10.0,77,21.0,29.98,0
100455,1.051071,50,28,18.7,2,10.0,80,11.0,30.00,0
100456,1.021346,47,32,6.6,1,10.0,77,7.0,30.01,0

In [45]:
print(data.head())

   distance-to-solar-noon  temperature  wind-direction  wind-speed  sky-cover  \
0                0.859897           69              28         7.5          0
1                0.628535           69              28         7.5          0
2                0.397172           69              28         7.5          0
3                0.165810           69              28         7.5          0
4                0.065553           69              28         7.5          0

   visibility  humidity  average-wind-speed-(period)  \
0        10.0        75                          8.0
1        10.0        77                          5.0
2        10.0        70                          0.0
3        10.0        33                          0.0
4        10.0        21                          3.0

   average-pressure-(period)  power-generated
0                      29.82                0
1                      29.85                0
2                      29.89             5418
3                      29.91            25477
4                      29.89            30069

In [51]:
print("\nChecking for missing values:")
print(data.isnull().sum())
if 'Unnamed: 0' in data.columns:
    data = data.drop(['Unnamed: 0'], axis=1)

Checking for missing values:
distance-to-solar-noon          0
temperature                     0
wind-direction                  0
wind-speed                      0
sky-cover                       0
visibility                      0
humidity                        0
average-wind-speed-(period)    35
average-pressure-(period)       0
power-generated                 0
dtype: int64

In [35]:
data.columns = data.columns.str.strip()

In [37]:
print("Columns in dataset:", data.columns)

Columns in dataset: Index(['distance-to-solar-noon', 'temperature', 'wind-direction', 'wind-speed',
       'sky-cover', 'visibility', 'humidity', 'average-wind-speed-(period)',
       'average-pressure-(period)', 'power-generated'],
      dtype='object')

In [53]:
target_column = "power_generated"
if target_column not in data.columns:
    possible_matches = [col for col in data.columns if "power" in col.lower()]
    if possible_matches:
        target_column = possible_matches[0] 
        print(f"Using '{target_column}' as target variable.")
    else:
        raise KeyError("Target column 'power_generated' not found. Check dataset.")

Using 'power-generated' as target variable.

In [55]:
X = data.drop(columns=[target_column])
y = data[target_column]

In [65]:
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("\nModel Evaluation:")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Mean Absolute Error: {mae:.2f}")
print(f"R-Squared Score: {r2:.2f}")
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color="blue", alpha=0.6)
plt.plot([y.min(), y.max()], [y.min(), y.max()], '--', color="red")
plt.xlabel("Actual Power Generated (Joules)")
plt.ylabel("Predicted Power Generated (Joules)")
plt.title("Actual vs Predicted Solar Power Generation")
plt.show()

NameError: name 'LinearRegression' is not defined